{{- $fullName := include "application.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  name: {{ $fullName }}
spec:
  {{- range .Values.ingress.hosts }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: ops-equiplano
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
