apiVersion: v1
kind: Secret
metadata:
    name: {{ include "application.fullname" . }}-secret
    labels:
      {{- include "application.selectorLabels" . | nindent 6 }}
type: Opaque
data:
{{- with .Values.secrets }}
    {{- toYaml . | nindent 2 }}
{{- end }}